### ISSUE TITLE
Notes on the Synthesis of Form

### ISSUE THREAD

**Issue by bjornmeansbear** [GD399-OSD/another-green-world#1]
Did I lend you that book? (I know I lent it to someone semi-recently) 
Its a gem.

**Comment by bjornmeansbear** [comment]
I hadn't seen that Ryan Singer talk before, wonderful. I've been struggling to find good ways to actually apply that thinking to my everyday design tasks... that helps!

**Comment by devinhalladay** [comment]
Nope, you didn't lend it to me, I've just been reading a PDF!

But yeah that Ryan Singer talk is great. I think there are some cool ideas that he wasn't able to articulate as well as needed & also maybe he skipped over some of the cooler ideas, so I think this particular piece will just be filling in the gaps & also figuring out how this can apply to my real process with clients.
